language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 420ef3d03ea51ad3631ccbf650a45a12ff1df1e0
  local_dir: build
  on:
    branch: master