language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: e685def32a7cf91fd91bc240e21800086106098d
  local_dir: build
  on:
    branch: master