export const GET_CITIES = 'GET_CITIES';
export const ADD_CITY = 'ADD_CITY';

export const FORECAST_REQUEST = 'FORECAST_REQUEST';
export const FORECAST_SUCCESS = 'FORECAST_SUCCESS';
export const FORECAST_FAILURE = 'FORECAST_FAILURE';

export const SEARCH_LOCATION_REQUEST = 'SEARCH_LOCATION_REQUEST';
export const SEARCH_LOCATION_SUCCESS = 'SEARCH_LOCATION_SUCCESS';
export const SEARCH_LOCATION_FAILURE = 'SEARCH_LOCATION_FAILURE';

export const GEOLOCATION_REQUEST = 'GEOLOCATION_REQUEST';
export const GEOLOCATION_SUCCESS = 'GEOLOCATION_SUCCESS';
export const GEOLOCATION_FAILURE = 'GEOLOCATION_FAILURE';